-- Postgres counterpart of schema.sql, used when DATABASE_URL points at a
-- server. Kept as a separate file rather than generated, so the deployed
-- schema is readable rather than inferred.
--
-- Differences from the SQLite version, all forced by the engine:
--   * IDENTITY instead of AUTOINCREMENT;
--   * BOOLEAN instead of INTEGER 0/1 - the Python code passes real bools, so
--     both engines accept the same parameters;
--   * timestamps stay TEXT in ISO-8601 UTC, matching SQLite, so the migration
--     copies values across unchanged rather than reinterpreting them.

CREATE TABLE IF NOT EXISTS links (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url            TEXT    NOT NULL,
    canonical_url  TEXT,
    platform       TEXT    NOT NULL,
    title          TEXT,
    caption        TEXT,
    location       TEXT,
    region         TEXT,
    category       TEXT,
    subcategory    TEXT,
    tags           TEXT,
    added_by       BIGINT  NOT NULL,
    added_at       TEXT    NOT NULL,
    done           BOOLEAN NOT NULL DEFAULT FALSE,
    done_at        TEXT,
    done_by        BIGINT,
    rating         INTEGER,
    note           TEXT,
    photo_file_id  TEXT,
    event_start    TEXT,
    event_end      TEXT,
    is_evergreen   BOOLEAN NOT NULL DEFAULT TRUE,
    lat            DOUBLE PRECISION,
    lng            DOUBLE PRECISION,
    parsed_at      TEXT
);

-- Columns added after the first deployment. CREATE TABLE IF NOT EXISTS skips an
-- existing table, so new columns need an explicit, idempotent ALTER here - the
-- Postgres equivalent of the SQLite migration in database.py.
ALTER TABLE links ADD COLUMN IF NOT EXISTS geocoded_at    TEXT;
ALTER TABLE links ADD COLUMN IF NOT EXISTS geocode_status TEXT;

-- The shared calendar reuses `availability`. It was drafted for structured
-- free/busy, but what is actually wanted is "gym then free after 8" - prose,
-- not a rigid schedule - so the note lives in its own column and `available`
-- goes unused. `slot` keeps its NOT NULL and is written as 'day', since a note
-- covers the whole day rather than a time slot.
ALTER TABLE availability ADD COLUMN IF NOT EXISTS note        TEXT;
ALTER TABLE availability ADD COLUMN IF NOT EXISTS author_name TEXT;

CREATE INDEX IF NOT EXISTS idx_links_url       ON links (url);
CREATE INDEX IF NOT EXISTS idx_links_canonical ON links (canonical_url);
CREATE INDEX IF NOT EXISTS idx_links_done      ON links (done);

CREATE TABLE IF NOT EXISTS dates (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label     TEXT    NOT NULL,
    date      TEXT    NOT NULL,
    recurring BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS availability (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT  NOT NULL,
    day       TEXT    NOT NULL,
    slot      TEXT    NOT NULL,
    available BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS plans (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_of    TEXT NOT NULL,
    summary    TEXT NOT NULL,
    created_at TEXT NOT NULL
);
