-- Postgres counterpart of schema.sql, used when DATABASE_URL points at a
-- server. Kept as a separate file rather than generated, so the deployed
-- schema is readable rather than inferred.
--
-- Differences from the SQLite version, all forced by the engine:
--   * IDENTITY instead of AUTOINCREMENT;
--   * BOOLEAN instead of INTEGER 0/1 - the Python code passes real bools, so
--     both engines accept the same parameters;
--   * timestamps stay TEXT in ISO-8601 UTC, matching SQLite, so the migration
--     copies values across unchanged rather than reinterpreting them.

CREATE TABLE IF NOT EXISTS links (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url            TEXT    NOT NULL,
    canonical_url  TEXT,
    platform       TEXT    NOT NULL,
    title          TEXT,
    caption        TEXT,
    location       TEXT,
    region         TEXT,
    category       TEXT,
    subcategory    TEXT,
    tags           TEXT,
    added_by       BIGINT  NOT NULL,
    added_at       TEXT    NOT NULL,
    done           BOOLEAN NOT NULL DEFAULT FALSE,
    done_at        TEXT,
    done_by        BIGINT,
    rating         INTEGER,
    note           TEXT,
    photo_file_id  TEXT,
    event_start    TEXT,
    event_end      TEXT,
    is_evergreen   BOOLEAN NOT NULL DEFAULT TRUE,
    lat            DOUBLE PRECISION,
    lng            DOUBLE PRECISION,
    parsed_at      TEXT
);

CREATE INDEX IF NOT EXISTS idx_links_url       ON links (url);
CREATE INDEX IF NOT EXISTS idx_links_canonical ON links (canonical_url);
CREATE INDEX IF NOT EXISTS idx_links_done      ON links (done);

CREATE TABLE IF NOT EXISTS dates (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label     TEXT    NOT NULL,
    date      TEXT    NOT NULL,
    recurring BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS availability (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT  NOT NULL,
    day       TEXT    NOT NULL,
    slot      TEXT    NOT NULL,
    available BOOLEAN NOT NULL DEFAULT FALSE
);

-- Values the couple can change from the Mini App; see CLAUDE.md.
CREATE TABLE IF NOT EXISTS settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Telegram retries a webhook delivery it does not get a prompt 200 for, and on
-- a host that sleeps the first delivery can still complete after the retry has
-- been sent. Claiming the update_id here makes processing at-most-once.
CREATE TABLE IF NOT EXISTS processed_updates (
    update_id BIGINT  PRIMARY KEY,
    seen_at   TEXT    NOT NULL,
    -- A claim released after a mid-handler failure so Telegram's retry can
    -- take it, with a count so a permanently failing update stops rather than
    -- looping for as long as Telegram keeps trying.
    attempts  INTEGER NOT NULL DEFAULT 1,
    failed    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS plans (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_of    TEXT NOT NULL,
    summary    TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Photos attached to a link. See schema.sql for why `kind` exists: an intake
-- screenshot is model input, a visit photo is a memory, and the two must never
-- be confused. BIGINT for added_by, matching links.added_by - Telegram user ids
-- outgrew INTEGER years ago.
CREATE TABLE IF NOT EXISTS link_photos (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id       INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE,
    file_id       TEXT    NOT NULL,
    thumb_file_id TEXT,
    kind          TEXT    NOT NULL,
    added_by      BIGINT,
    added_at      TEXT    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_link_photos_file ON link_photos (link_id, file_id);
CREATE INDEX IF NOT EXISTS idx_link_photos_link ON link_photos (link_id, kind, id);

-- ---------------------------------------------------------------------
-- Migrations. These run AFTER every CREATE TABLE above, because ALTER on
-- a table this script has not created yet fails on a fresh database.
-- ---------------------------------------------------------------------

-- Columns added after the first deployment. CREATE TABLE IF NOT EXISTS skips an
-- existing table, so new columns need an explicit, idempotent ALTER here - the
-- Postgres equivalent of the SQLite migration in database.py.
ALTER TABLE links ADD COLUMN IF NOT EXISTS geocoded_at    TEXT;
ALTER TABLE links ADD COLUMN IF NOT EXISTS geocode_status TEXT;

-- The shared calendar reuses `availability`. It was drafted for structured
-- free/busy, but what is actually wanted is "gym then free after 8" - prose,
-- not a rigid schedule - so the note lives in its own column and `available`
-- goes unused. `slot` keeps its NOT NULL and is written as 'day', since a note
-- covers the whole day rather than a time slot.
ALTER TABLE availability ADD COLUMN IF NOT EXISTS note          TEXT;
ALTER TABLE availability ADD COLUMN IF NOT EXISTS author_name   TEXT;
-- Per-entry reminder milestones, so a calendar note can announce on its own
-- schedule instead of a single hardcoded one.
ALTER TABLE availability ADD COLUMN IF NOT EXISTS reminder_days TEXT;

-- `recurring` was a boolean, which cannot express a monthsary. `recurrence`
-- replaces it with once|monthly|yearly; the old column is left in place and
-- backfilled rather than dropped.
ALTER TABLE dates ADD COLUMN IF NOT EXISTS recurrence    TEXT;
ALTER TABLE dates ADD COLUMN IF NOT EXISTS reminder_days TEXT;
UPDATE dates SET recurrence = CASE WHEN recurring THEN 'yearly' ELSE 'once' END
 WHERE recurrence IS NULL;

-- processed_updates predates the retry counters, so they are added here for a
-- database created before at-least-once delivery existed.
ALTER TABLE processed_updates ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 1;
ALTER TABLE processed_updates ADD COLUMN IF NOT EXISTS failed   BOOLEAN NOT NULL DEFAULT FALSE;
